parameters:

services:
    acilia.banners:
        class: Acilia\Bundle\BannerBundle\Service\BannerService
        arguments: ["@event_dispatcher", "@request_stack", "@doctrine", "@core.memcached", %acilia.banner.place_fallbacks%]

    acilia.banners.twig_extension:
        class: Acilia\Bundle\BannerBundle\Library\Twig\Extension\BannerExtension
        arguments: ["@acilia.banners"]
        tags:
          - { name: twig.extension }

    # Init Listener
    acilia.banners.listener.init:
        class: Acilia\Bundle\BannerBundle\EventListener\InitListener
        arguments: ["@acilia.banners", "@user_agent"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 17 }