parameters:

services:
    acilia.banners:
        class: Acilia\Bundle\BannerBundle\Service\BannerService
        arguments: [@event_dispatcher, @request_stack, @doctrine, @core.memcached, %acilia.banner.place_fallbacks%]

    acilia.banners.twig_extension:
        class: Acilia\Bundle\BannerBundle\Library\Twig\Extension\BannerExtension
        arguments: [@acilia.banners]
        tags:
          - { name: twig.extension }
